# Generated by Django 6.0.2 on 2026-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='user_nickname'),
        ),
    ]
